name: CardioBit Software CI

on:
  push:
    paths:
      - 'software/**'
    branches: [ main, master ]
  pull_request:
    paths:
      - 'software/**'
    branches: [ main, master ]

jobs:
  # --- JOB 1: Statyczna Analiza Kodu ---
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --inline-suppr --std=c++17 \
                 --error-exitcode=1 \
                 software/CardioBit/Core/Src \
                 software/CardioBit/Core/Inc \
                 software/CardioBit/Core/Tasks

  # --- JOB 2: Kompilacja projektu ---
  build:
    runs-on: ubuntu-latest
    needs: static-analysis 
    defaults:
      run:
        working-directory: software/CardioBit
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install ARM Toolchain
      uses: emilianis/install-arm-none-eabi-gcc@v2
      with:
        release: '13.3.Rel1'

    - name: Install Ninja & CMake
      run: sudo apt-get install -y ninja-build cmake

    - name: Configure CMake
      run: |
        cmake -S . -B build -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE=cmake/gcc-arm-none-eabi.cmake \
        -DCMAKE_BUILD_TYPE=Debug

    - name: Build Project
      run: cmake --build build
